### ISSUE TITLE
KitwareMedicalPublications

### ISSUE THREAD

**Issue by aylward** [KitwareMedical/2019-03-13-KRSCourseInBiomedicalImageAnalysisAndVisualization#33]
Should this be moved to the KitwareMedicalPublications github account?

**Comment by thewtex** [comment]
I attempted a transfer. It did not go through, or GitHub is taking a while...

It is worth noting that next time we give the course, we were planning to remove the date from the repo name, and continuously update the repository.

**Comment by thewtex** [comment]
Repository renamed for continued use.
