### ISSUE TITLE
Update Registration

### ISSUE THREAD

**Issue by thewtex** [KitwareMedical/2019-03-13-KRSCourseInBiomedicalImageAnalysisAndVisualization#6]
- [x] Exercises [use %load](https://github.com/glemaitre/pyparis-2018-sklearn/blob/master/notebook.ipynb)
- [x] Add another registration example
- [x] Make sure that there is a good explanation for backward vs forward transform
- [x] Update cell 4 to point to updated slides

**Comment by bpaniagua** [comment]
@thewtex the tooth segmentation code will not be ready.
Do you want to include the corpus callosum segmentation notebook here #4

**Comment by dzenanz** [comment]
@bpaniagua remove yourself from the assignees list if you don't want to get further updates.

**Comment by thewtex** [comment]
@bpaniagua yes, agreed. We'll punt on the tooth segmentation / registration for now.
